# UI Configuration for RAGE
branding:
  title: "RAGE - Retrieval Augmented Generation Environment"
  favicon: "assets/favicon.ico"
  logo: "assets/rage_logo.png"
  user_icon: "assets/user_icon.png"
  assistant_icon: "assets/assistant_icon.png"

prompts:
  system_prompt_file: "prompts/system_prompt.txt"
  user_prompt_template: "prompts/user_prompt.txt"
  rag_prompt_template: "prompts/rag_prompt.txt"

styles:
  primary_color: "#00cc00"
  secondary_color: "#262730"
  accent_color: "#58a6ff"
  background_color: "#0E1117"
